// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.UIKit;
using HalalGuide.iOS.Util;

namespace HalalGuide.iOS.Tables.Cells
{
	public partial class CategoryCell : BaseTableViewCell
	{
		public static string Identifier = "CategoryCell";

		public CategoryCell (IntPtr handle) : base (handle)
		{
		}

		public CategoryCell (UITableViewCellStyle style, string categoryCellIdentifier) : base (style, categoryCellIdentifier)
		{

		}


	}
}
