// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace HalalGuide.iOS
{
	public partial class CategoryCell : UITableViewCell
	{
		public CategoryCell (IntPtr handle) : base (handle)
		{
		}

		public CategoryCell (UITableViewCellStyle style, string categoryCellIdentifier) : base (style, categoryCellIdentifier)
		{

		}
	}
}
