// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.UIKit;
using MonoTouch.Foundation;

namespace HalalGuide.iOS.Tables.Cells
{
	[Register ("CategoryCell")]
	public class CategoryCell : BaseTableViewCell
	{
		public static string Identifier = "CategoryCell";

		public CategoryCell (IntPtr handle) : base (handle)
		{
		}

		public CategoryCell (UITableViewCellStyle style, string categoryCellIdentifier) : base (style, categoryCellIdentifier)
		{

		}
	}
}
