// This file has been autogenerated from a class added in the UI designer.
using System;
using MonoTouch.UIKit;
using HalalGuide.Domain;
using HalalGuide.Util;
using MonoTouch.Foundation;

namespace HalalGuide.iOS.Tables.Cells
{
	[Register ("DiningCell")]
	public  class DiningCell : LocationCell
	{
		public DiningCell (IntPtr handle) : base (handle)
		{
		}

		public override void ConfigureLocation (Location l)
		{
			base.ConfigureLocation (l);

			UIImageView firstImage = (UIImageView)ViewWithTag (PigImageTag);
			firstImage.Image = UIImage.FromBundle (Images.Pig + l.pork);

			UIImageView secondImage = (UIImageView)ViewWithTag (AlcoholImageTag);
			secondImage.Image = UIImage.FromBundle (Images.Alcohol + l.alcohol);

			UIImageView thirdImage = (UIImageView)ViewWithTag (HalalImageTag);
			thirdImage.Image = UIImage.FromBundle (Images.NonHalal + l.nonHalal);

			UILabel firstLabel = (UILabel)ViewWithTag (PigLabelTag);
			firstLabel.TextColor = l.pork ? UIColor.Red : UIColor.Green;

			UILabel secondLabel = (UILabel)ViewWithTag (AlcoholLabelTag);
			secondLabel.TextColor = l.alcohol ? UIColor.Red : UIColor.Green;

			UILabel thirdLabel = (UILabel)ViewWithTag (HalalLabelTag);
			thirdLabel.TextColor = l.nonHalal ? UIColor.Red : UIColor.Green;

		}
	}
}