// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using MonoTouch.AddressBook;
using MonoTouch.CoreImage;
using HalalGuide.Domain;
using HalalGuide.Util;

namespace HalalGuide.iOS
{
	public partial class DiningCell : UITableViewCell
	{

		public static readonly int CategoryImageTag = 101;
		public static readonly int PigImageTag = 102;
		public static readonly int AlcoholImageTag = 103;
		public static readonly int HalalImageTag = 104;

		public static readonly int NameLabelTag = 201;
		public static readonly int AddressLabelTag = 202;
		public static readonly int PostalCodeLabelTag = 203;
		public static readonly int PigLabelTag = 204;
		public static readonly int AlcoholLabelTag = 205;
		public static readonly int HalalLabelTag = 206;

		public DiningCell (IntPtr handle) : base (handle)
		{


		}



		public void ConfigureLocation (Location l)
		{
			UIImageView category = (UIImageView)ViewWithTag (CategoryImageTag);
			category.Image = UIImage.FromBundle (Constants.landingPage + l.LocationType);

			UILabel name = (UILabel)ViewWithTag (NameLabelTag);
			name.Text = l.Name;

			UILabel address1 = (UILabel)ViewWithTag (AddressLabelTag);
			address1.Text = l.AddressRoad;
			UILabel address2 = (UILabel)ViewWithTag (PostalCodeLabelTag);
			address2.Text = l.AddressPostalCode + " " + l.AddressCity;

			UIImageView firstImage = (UIImageView)ViewWithTag (PigImageTag);
			firstImage.Image = UIImage.FromBundle (Constants.DiningAttributePig + l.Pork);

			UIImageView secondImage = (UIImageView)ViewWithTag (AlcoholImageTag);
			secondImage.Image = UIImage.FromBundle (Constants.DiningAttributeAlcohol + l.Alcohol);

			UIImageView thirdImage = (UIImageView)ViewWithTag (HalalImageTag);
			thirdImage.Image = UIImage.FromBundle (Constants.DiningAttributeHalal + l.NonHalal);

			UILabel firstLabel = (UILabel)ViewWithTag (PigLabelTag);
			firstLabel.TextColor = l.Pork ? UIColor.Red : UIColor.Green;

			UILabel secondLabel = (UILabel)ViewWithTag (AlcoholLabelTag);
			secondLabel.TextColor = l.Alcohol ? UIColor.Red : UIColor.Green;

			UILabel thirdLabel = (UILabel)ViewWithTag (HalalLabelTag);
			thirdLabel.TextColor = l.NonHalal ? UIColor.Red : UIColor.Green;

		}
	}
}
