// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.UIKit;
using HalalGuide.Util;
using HalalGuide.Domain;
using MonoTouch.Foundation;

namespace HalalGuide.iOS.Tables.Cells
{
	[Register ("MosqueCell")]
	public class MosqueCell : LocationCell
	{
		public MosqueCell (IntPtr handle) : base (handle)
		{
		}

		public override void ConfigureLocation (Location l)
		{
			base.ConfigureLocation (l);
			UIImageView firstImage = (UIImageView)ViewWithTag (LaguageImageTag);
			firstImage.Image = UIImage.FromBundle (l.language.ToString ());

			UILabel firstLabel = (UILabel)ViewWithTag (LanguageLabelTag);
			firstLabel.Text = l.language.ToString ().ToLower ().FirstToUpper ();

		}

	}
}
