// This file has been autogenerated from a class added in the UI designer.
using System;

using MonoTouch.UIKit;
using System.Drawing;

namespace HalalGuide.iOS
{
	public partial class ReviewCell : UITableViewCell
	{
		public UIImageView Star1Image { get; internal set; }

		public UIImageView Star2Image{ get; internal set; }

		public UIImageView Star3Image{ get; internal set; }

		public UIImageView Star4Image{ get; internal set; }

		public UIImageView Star5Image{ get; internal set; }

		public UILabel Review{ get; internal set; }

		public UILabel Submitter{ get; internal set; }

		public ReviewCell (IntPtr handle) : base (handle)
		{
			Configure ();
		}

		public ReviewCell (UITableViewCellStyle style, string reuseIdentifier) : base (style, reuseIdentifier)
		{
			Configure ();
		}

		private void Configure ()
		{
			Star1Image = new UIImageView (new RectangleF (20, 12, 20, 20));
			Star2Image = new UIImageView (new RectangleF (46, 12, 20, 20));
			Star3Image = new UIImageView (new RectangleF (72, 12, 20, 20));
			Star4Image = new UIImageView (new RectangleF (98, 12, 20, 20));
			Star5Image = new UIImageView (new RectangleF (124, 12, 20, 20));

			AddSubviews (Star1Image, Star2Image, Star3Image, Star4Image, Star5Image);

			Submitter = new UILabel (new RectangleF (158, 12, 146, 21)) {
				TextAlignment = UITextAlignment.Right
			};
			Review = new UILabel (new RectangleF (20, 40, 284, 42)) {
				Lines = 2,
				Font = UIFont.SystemFontOfSize (13)

			};
			AddSubviews (Submitter, Review);
		}
		
	}
}
