// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using HalalGuide.Domain;
using HalalGuide.Util;
using HalalGuide.iOS.Tables.Cells;

namespace HalalGuide.iOS
{
	public partial class ShopCell : LocationCell
	{
		public ShopCell (IntPtr handle) : base (handle)
		{
		}

		public override void ConfigureLocation (Location l)
		{
			base.ConfigureLocation (l);
		}
	}
}
