// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using HalalGuide.Domain;
using HalalGuide.Util;

namespace HalalGuide.iOS
{
	public partial class ShopCell : UITableViewCell
	{
		public static readonly int CategoryImageTag = 101;

		public static readonly int NameLabelTag = 201;
		public static readonly int AddressLabelTag = 202;
		public static readonly int PostalCodeLabelTag = 203;

		public ShopCell (IntPtr handle) : base (handle)
		{
		}

		public void ConfigureLocation (Location l)
		{
			UIImageView category = (UIImageView)ViewWithTag (CategoryImageTag);
			category.Image = UIImage.FromBundle (Constants.landingPage + l.LocationType);

			UILabel name = (UILabel)ViewWithTag (NameLabelTag);
			name.Text = l.Name;

			UILabel address1 = (UILabel)ViewWithTag (AddressLabelTag);
			address1.Text = l.AddressRoad;
			UILabel address2 = (UILabel)ViewWithTag (PostalCodeLabelTag);
			address2.Text = l.AddressPostalCode + " " + l.AddressCity;
		}
	}
}
