// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;

namespace HalalGuide.iOS.Tables.Cells
{
	[Register ("ShopCell")]
	public partial class ShopCell : LocationCell
	{
		public ShopCell (IntPtr handle) : base (handle)
		{
		}
	}
}
