// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.UIKit;

namespace HalalGuide.iOS.ViewController.Table
{
	public partial class AddNewDiningTableViewController : UITableViewController
	{
		public AddNewDiningTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
