// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace HalalGuideiOS
{
	public partial class DiningViewController : UIViewController
	{
		public DiningViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
