// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace HalalGuide.iOS
{
	public partial class LandingPageController : UIViewController
	{
		public LandingPageController (IntPtr handle) : base (handle)
		{
		}
	}
}
