// This file has been autogenerated from a class added in the UI designer.

using System;

using HalalGuide.iOS.ViewController;
using MonoTouch.Foundation;
using HalalGuide.iOS.Util;
using HalalGuide.iOS.ViewController.Table;
using MonoTouch.UIKit;

namespace HalalGuide.iOS.ViewController
{
	public partial class AddNewDiningViewController : KeyboardSupportedUIViewController
	{
		AddNewDiningTableViewController childViewController;

		public AddNewDiningViewController (IntPtr handle) : base (handle)
		{
		}


		partial void Regret (NSObject sender)
		{
			DismissViewController (true, null);
		}

		async partial void Save (NSObject sender)
		{
			await childViewController.Save ((MonoTouch.UIKit.UIBarButtonItem)sender);
		}

		public override void PrepareForSegue (MonoTouch.UIKit.UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			if (segue.Identifier.Equals (Segue.AddDiningEmbedded)) {
				childViewController = (AddNewDiningTableViewController)segue.DestinationViewController;
			}
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			View.TranslateLabelsAndPlaceholders ();
			TranslateNavigationItem ();
		}

		[Export ("positionForBar:")]
		public  UIBarPosition GetPositionForBar (IUIBarPositioning barPositioning)
		{
			return UIBarPosition.TopAttached;
		}
	}

}
