// This file has been autogenerated from a class added in the UI designer.

using System;
using MonoTouch.Foundation;
using HalalGuide.iOS.ViewController;
using HalalGuide.iOS.Util;
using MonoTouch.UIKit;

namespace HalalGuide.iOS.ViewController
{
	public partial class FilterMultipleDiningViewController : KeyboardSupportedUIViewController
	{

		public FilterMultipleDiningViewController (IntPtr handle) : base (handle)
		{
		}

		partial void Done (UIBarButtonItem sender)
		{
			DismissViewController (true, null);
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			View.TranslateLabelsAndPlaceholders ();
			TranslateNavigationItem ();
		}

	}
}
