// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using System.Drawing;
using HalalGuide.Domain;
using HalalGuide.ViewModels;
using HalalGuide.iOS.Util;
using HalalGuide.iOS.Tables.Cells;
using HalalGuide.Services;

namespace HalalGuide.iOS.ViewController
{
	public partial class MultipleDiningViewController : KeyboardSupportedUIViewController, IUISearchBarDelegate
	{
		private const string cellIdentifier = "Dining";
		private const string searchCellIdentifier = "SearchCell";

		public MultipleDiningViewModel viewModel = ServiceContainer.Resolve<MultipleDiningViewModel> ();
		public SingleDiningViewModel singleDiningViewModel = ServiceContainer.Resolve<SingleDiningViewModel> ();

		private UITableViewController tableViewController = new UITableViewController ();
		private UIRefreshControl refreshControl = new UIRefreshControl ();

		private UISearchBar searchBar;

		public MultipleDiningViewController (IntPtr handle) : base (handle)
		{

		}

		public override void  ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SetupTableView ();

			SetupSearchBar ();

			SetupEventListeners ();

			viewModel.RefreshCache ();
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			DiningTableView.SetContentOffset (new PointF (0, searchBar.Frame.Size.Height), true);
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			if (Segue.SingleDiningViewControllerSegue.Equals (segue.Identifier)) {
				NSIndexPath indexPath = DiningTableView.IndexPathForCell ((UITableViewCell)sender);
				singleDiningViewModel.SelectedLocation = viewModel.GetLocationAtRow (indexPath.Item);
			}
		}

		#region Setup

		private void SetupTableView ()
		{
		
			DiningTableView.TableFooterView = new UIView ();

			tableViewController.TableView = DiningTableView;
			tableViewController.RefreshControl = refreshControl;

			refreshControl.ValueChanged += async (sender, e) => {
				refreshControl.BeginRefreshing ();
				await viewModel.RefreshLocations ();
				refreshControl.EndRefreshing ();

				UIView.Animate (
					0.2,
					() => {
						DiningTableView.SetContentOffset (new PointF (0, searchBar.Frame.Size.Height), true);
					}
				);
			};
		}

		private void SetupEventListeners ()
		{

			viewModel.RefreshedLocations += (sender, e) => InvokeOnMainThread (() => {
				DiningTableView.SetContentOffset (new PointF (0, searchBar.Frame.Size.Height), false);
				tableViewController.TableView.ReloadData ();
			});

			viewModel.filteredLocations += (sender, e) => InvokeOnMainThread (() => {
				tableViewController.TableView.ReloadData ();
			});

		}

		#endregion

		#region SearchBar

		private void SetupSearchBar ()
		{
			DiningTableView.TableHeaderView = searchBar = new UISearchBar (new RectangleF (0, 0, DiningTableView.Frame.Width, 44)) {
				BackgroundColor = UIColor.Clear
			};

			searchBar.ShowsCancelButton = true;
			searchBar.WeakDelegate = this;

		}

		[Export ("searchBar:textDidChange:")]
		public void TextChanged (UISearchBar searchBar, string searchText)
		{
			bool cacheChanged = viewModel.SearchTextChanged (searchText);
			if (cacheChanged) {
				DiningTableView.ReloadData ();
			}
		}


		[Export ("searchBarSearchButtonClicked:")]
		public  void SearchButtonClicked (UISearchBar searchBar)
		{
			bool cacheChanged = viewModel.SearchTextChanged (searchBar.Text);
			if (cacheChanged) {
				DiningTableView.ReloadData ();
			}
			searchBar.ResignFirstResponder ();
		}

		[Export ("searchBarCancelButtonClicked:")]
		public void CancelButtonClicked (UISearchBar searchBar)
		{
			searchBar.ResignFirstResponder ();
			searchBar.Text = ("");
			viewModel.SearchTextChanged ("");
			DiningTableView.ReloadData ();
			DiningTableView.SetContentOffset (new PointF (0, searchBar.Frame.Size.Height), true);
		}

		#endregion

		#region TableView

		[Export ("tableView:numberOfRowsInSection:")]
		public  int RowsInSection (UITableView tableview, int section)
		{
			return viewModel.Rows ();
		}

		[Export ("tableView:cellForRowAtIndexPath:")]
		public  UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{

			UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);
			Location l = viewModel.GetLocationAtRow (indexPath.Item);
			((DiningCell)cell).ConfigureLocation (l);
			return cell;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		public  void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			tableView.DeselectRow (indexPath, true); // normal iOS behaviour is to remove the blue highlight
		}

		#endregion



	}
}
