// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using XUbertestersSDK;
using System.Drawing;
using HalalGuide.Domain;
using SimpleDBPersistence.Service;
using HalalGuide.ViewModels;
using HalalGuide.iOS.Util;
using HalalGuide.iOS.Tables.Cells;

namespace HalalGuide.iOS.ViewController
{
	public partial class MultipleDiningViewController : KeyboardSupportedUIViewController, IUISearchBarDelegate
	{
		private const string cellIdentifier = "Dining";
		private const string SearchCellIdentifier = "SearchCell";

		public MultipleDiningViewModel ViewModel = ServiceContainer.Resolve<MultipleDiningViewModel> ();
		public SingleDiningViewModel SingleDiningViewModel = ServiceContainer.Resolve<SingleDiningViewModel> ();

		private UITableViewController TableViewController = new UITableViewController ();
		private UIRefreshControl RefreshControl = new UIRefreshControl ();

		private UISearchBar SearchBar;

		public MultipleDiningViewController (IntPtr handle) : base (handle)
		{

		}

		public override void  ViewDidLoad ()
		{
			base.ViewDidLoad ();

			SetupTableView ();

			SetupSearchBar ();

			SetupEventListeners ();
		}

		public override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);
			DiningTableView.SetContentOffset (new PointF (0, SearchBar.Frame.Size.Height), true);
			XUbertesters.LogInfo ("MultipleDiningViewController: ViewDidAppear");
		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			base.PrepareForSegue (segue, sender);

			if (Segue.SingleDiningViewControllerSegue.Equals (segue.Identifier)) {
				NSIndexPath indexPath = DiningTableView.IndexPathForCell ((UITableViewCell)sender);
				SingleDiningViewModel.SelectedLocation = ViewModel.GetLocationAtRow (indexPath.Item);
			}
		}

		#region Setup

		private void SetupTableView ()
		{
		
			DiningTableView.TableFooterView = new UIView ();

			TableViewController.TableView = DiningTableView;
			TableViewController.RefreshControl = RefreshControl;

			RefreshControl.ValueChanged += async (sender, e) => {
				RefreshControl.BeginRefreshing ();
				await ViewModel.RefreshLocations ();
				DiningTableView.ReloadData ();
				RefreshControl.EndRefreshing ();

				UIView.Animate (
					0.2,
					() => {
						DiningTableView.SetContentOffset (new PointF (0, SearchBar.Frame.Size.Height), true);
					}
				);
			};
		}

		private void SetupEventListeners ()
		{
			ViewModel.RefreshLocationsCompletedEvent += (sender, e) => InvokeOnMainThread (() => {
				DiningTableView.SetContentOffset (new PointF (0, SearchBar.Frame.Size.Height), false);
				TableViewController.TableView.ReloadSections (new NSIndexSet (0), UITableViewRowAnimation.Top);
			});

			ViewModel.FilteredLocations += (sender, e) => InvokeOnMainThread (() => {
				TableViewController.TableView.ReloadSections (new NSIndexSet (0), UITableViewRowAnimation.Top);
			});
		}



		#endregion

		#region SearchBar

		private void SetupSearchBar ()
		{
			DiningTableView.TableHeaderView = SearchBar = new UISearchBar (new RectangleF (0, 0, DiningTableView.Frame.Width, 44)) {
				BackgroundColor = UIColor.Clear
			};

			SearchBar.ShowsCancelButton = true;
			SearchBar.WeakDelegate = this;

		}

		[Export ("searchBar:textDidChange:")]
		public void TextChanged (UISearchBar searchBar, string searchText)
		{
			bool cacheChanged = ViewModel.SearchTextChanged (searchText);
			if (cacheChanged) {
				DiningTableView.ReloadData ();
			}
		}


		[Export ("searchBarSearchButtonClicked:")]
		public void SearchButtonClicked (UISearchBar searchBar)
		{
			bool cacheChanged = ViewModel.SearchTextChanged (searchBar.Text);
			if (cacheChanged) {
				DiningTableView.ReloadData ();
			}
			searchBar.ResignFirstResponder ();
		}

		[Export ("searchBarCancelButtonClicked:")]
		public void CancelButtonClicked (UISearchBar searchBar)
		{
			searchBar.ResignFirstResponder ();
			searchBar.Text = ("");
			ViewModel.SearchTextChanged ("");
			DiningTableView.ReloadData ();
			DiningTableView.SetContentOffset (new PointF (0, SearchBar.Frame.Size.Height), true);
		}

		#endregion

		#region TableView

		[Export ("tableView:numberOfRowsInSection:")]
		public  int RowsInSection (UITableView tableview, int section)
		{
			return ViewModel.Rows ();
		}

		[Export ("tableView:cellForRowAtIndexPath:")]
		public  UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{

			UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);
			Location l = ViewModel.GetLocationAtRow (indexPath.Item);
			((DiningCell)cell).ConfigureLocation (l);
			return cell;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		public  void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			tableView.DeselectRow (indexPath, true); // normal iOS behaviour is to remove the blue highlight
		}

		#endregion



	}
}
