// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using HalalGuide.ViewModels;
using XUbertestersSDK;
using System.Drawing;
using HalalGuide.Util;
using HalalGuide.Domain;
using SimpleDBPersistence.Service;

namespace HalalGuide.iOS.ViewController
{
	public partial class MultipleDiningViewController : UIViewController
	{
		private const string cellIdentifier = "Dining";

		public MultipleDiningViewModel ViewModel = ServiceContainer.Resolve<MultipleDiningViewModel> ();

		private UITableViewController TableViewController = new UITableViewController ();
		private UIRefreshControl RefreshControl = new UIRefreshControl ();

		UISearchBar SearchBar;

		private UIViewController Login;

		public MultipleDiningViewController (IntPtr handle) : base (handle)
		{

		}

		public override void  ViewDidLoad ()
		{
			XUbertesters.LogInfo ("DiningPageController: ViewDidLoad-Start");
			base.ViewDidLoad ();

			SetupTableView ();

			SetupEventListeners ();

			XUbertesters.LogInfo ("DiningPageController: ViewDidLoad-End");
		}

		public async override void  ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);

			await ViewModel.Update ();
		}

		#region Setup

		private void SetupTableView ()
		{
		
			DiningTableView.TableFooterView = new UIView ();

			TableViewController.TableView = DiningTableView;
			TableViewController.RefreshControl = RefreshControl;

			RefreshControl.ValueChanged += async (sender, e) => {
				RefreshControl.BeginRefreshing ();
				await ViewModel.Update ();
				RefreshControl.EndRefreshing ();

				UIView.Animate (
					0.2,
					() => {
						TableViewController.TableView.ContentInset = new UIEdgeInsets (0, 0, 0, 0);
					}
				);
			};

			TableViewController.TableView.AddSubview (SearchBar = new UISearchBar (new RectangleF (0, -44, DiningTableView.Frame.Width, 44)) {
				BackgroundColor = UIColor.Clear
			});
		}

		private void SetupEventListeners ()
		{

			ViewModel.LoadedListEvent += (sender, e) => InvokeOnMainThread (() => TableViewController.TableView.ReloadSections (new NSIndexSet (0), UITableViewRowAnimation.Top));

			//TODO move to base class
			/*
			ViewModel.LoginCompletedEvent += (object sender, AuthenticatorCompletedEventArgs e) => {
				if (Login != null) {
					Login.DismissViewController (true, delegate {

						if (e.IsAuthenticated) {
							PerformSegue (Segue.AddDiningSegue, this);

						} else {
							UIAlertView view = new UIAlertView ("Fejl", "Login fejlede, du skal bekræfte din identitet inden du kan tilføje emner til HalalGuide", null, "Luk");
							view.Show ();
						}
					});
					Login = null;
				}
			};
			*/
		}

		#endregion

		public override bool ShouldPerformSegue (string segueIdentifier, NSObject sender)
		{
			XUbertesters.LogInfo ("DiningPageController: ShouldPerformSegue-Start");
			if (segueIdentifier != null && segueIdentifier.Equals (Segue.AddNewDiningViewControllerSegue)) {

				if (ViewModel.IsAuthenticated ()) {
					XUbertesters.LogInfo ("DiningPageController: ShouldPerformSegue-End");
					return true;
				} else {
					/*
					var auth = ViewModel.Authenticate ();
					PresentViewController (Login = auth.GetUI (), true, null);
					*/
					XUbertesters.LogInfo ("DiningPageController: ShouldPerformSegue-End");
					return false;
				}
			} else {
				XUbertesters.LogInfo ("DiningPageController: ShouldPerformSegue-End");
				return true;
			}


		}

		public override void PrepareForSegue (UIStoryboardSegue segue, NSObject sender)
		{
			if (Segue.SingleDiningViewControllerSegue.Equals (segue.Identifier)) {
				NSIndexPath indexPath = DiningTableView.IndexPathForCell ((UITableViewCell)sender);
				BaseViewModel.SelectedLocation = ViewModel.GetLocationAtRow (indexPath.Item);
			}
		}

		[Export ("scrollViewDidEndDragging:willDecelerate:")]
		public  void DraggingEnded (UIScrollView scrollView, bool willDecelerate)
		{
			if (willDecelerate) {
				SearchBar.ResignFirstResponder ();
			}
			if (scrollView.ContentOffset.Y < 0) {
				UIView.Animate (
					0.2,
					() => {
						TableViewController.TableView.ContentInset = new UIEdgeInsets (44, 0, 0, 0);
					}
				);
			} else {
				UIView.Animate (
					0.2,
					() => {
						TableViewController.TableView.ContentInset = new UIEdgeInsets (0, 0, 0, 0);
					}
				);
			}
		}

		#region TableView

		[Export ("tableView:numberOfRowsInSection:")]
		public  int RowsInSection (UITableView tableview, int section)
		{
			return ViewModel.Rows ();
		}

		[Export ("tableView:cellForRowAtIndexPath:")]
		public  UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			UITableViewCell cell = tableView.DequeueReusableCell (cellIdentifier);

			Location l = ViewModel.GetLocationAtRow (indexPath.Item);

			((DiningCell)cell).ConfigureLocation (l);

			return cell;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		public  void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			tableView.DeselectRow (indexPath, true); // normal iOS behaviour is to remove the blue highlight
		}

		#endregion



	}
}
