// This file has been autogenerated from a class added in the UI designer.

using System;

using HalalGuide.ViewModels;
using SimpleDBPersistence.Service;
using MonoTouch.UIKit;

namespace HalalGuide.iOS.ViewController
{
	public partial class SingleDiningViewController : BaseViewController
	{
		private readonly SingleDiningViewModel SingleDiningViewModel = ServiceContainer.Resolve<SingleDiningViewModel> ();

		public SingleDiningViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			NavigationItem.Title = SingleDiningViewModel.SelectedLocation.Name;
		}
	}
}

