// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;

namespace HalalGuide.iOS
{
	public partial class DismissSeque : UIStoryboardSegue
	{
		public DismissSeque (IntPtr handle) : base (handle)
		{
		}

		public override void Perform ()
		{
			UIViewController sourceViewController = this.SourceViewController;
			sourceViewController.PresentingViewController.DismissViewController (true, null); //dismissViewControllerAnimated:YES completion:nil];

		}
	}
}
