
// This file has been autogenerated from a class added in the UI designer.

using System;

using MonoTouch.Foundation;
using MonoTouch.UIKit;
using HalalGuide.Domain;
using HalalGuide.Domain.Enum;
using HalalGuide.ViewModels;
using SimpleDBPersistence.Service;
using HalalGuide.Util;
using XUbertestersSDK;

namespace HalalGuide.iOS
{
	public partial class LandingPageController : UIViewController
	{
		public LatestViewModel ViewModel = ServiceContainer.Resolve<LatestViewModel> ();

		private UITableViewController ViewController = new UITableViewController ();
		private UIRefreshControl RefreshControl = new UIRefreshControl ();

		public LandingPageController (IntPtr handle) : base (handle)
		{
		}

		public async override void  ViewDidLoad ()
		{
			XUbertesters.LogInfo ("LandingPageController: ViewDidLoad-Start");
			base.ViewDidLoad ();

			SetupTableView ();

			SetupEventListeners ();

			XUbertesters.LogInfo ("LandingPageController: ViewDidLoad-End");
		}

		public async override void ViewDidAppear (bool animated)
		{
			base.ViewDidAppear (animated);

			await ViewModel.Update ();
			//PerformSegue (Segue.DiningViewSeque, this);
		}

		#region Setup

		private void SetupTableView ()
		{

			LatestUpdated.WeakDelegate = this;
			LatestUpdated.WeakDataSource = this;

			ViewController.TableView = LatestUpdated;
			ViewController.RefreshControl = RefreshControl;
			RefreshControl.ValueChanged += async (sender, e) => {
				RefreshControl.BeginRefreshing ();
				await ViewModel.Update ();
				RefreshControl.EndRefreshing ();
			};
		}

		private void SetupEventListeners ()
		{
			ViewModel.LoadedListEvent += (sender, e) => InvokeOnMainThread (() => ViewController.TableView.ReloadSections (new NSIndexSet (0), UITableViewRowAnimation.Top));
		}

		#endregion

		#region TableView

		[Export ("tableView:numberOfRowsInSection:")]
		public  int RowsInSection (UITableView tableview, int section)
		{
			return ViewModel.Rows ();
		}

		[Export ("tableView:cellForRowAtIndexPath:")]
		public  UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			Location l = ViewModel.GetLocationAtRow (indexPath.Item);

			UITableViewCell cell = tableView.DequeueReusableCell (l.LocationType.ToString ());

			switch (l.LocationType) {
			case LocationType.Dining:
				{
					((DiningCell)cell).ConfigureLocation (l);
					break;
				}
			case LocationType.Shop:
				{
					((ShopCell)cell).ConfigureLocation (l);
					break;
				}
			case LocationType.Mosque:
				{
					((MosqueCell)cell).ConfigureLocation (l);
					break;
				}
			}

			return cell;
		}

		[Export ("tableView:didSelectRowAtIndexPath:")]
		public  void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			tableView.DeselectRow (indexPath, true); // normal iOS behaviour is to remove the blue highlight
		}

		#endregion
	}
}
